management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
  tomcat:
    threads:
      max: 500


privilegeservice:
  login:
    multiply: false
    ExpireTime: 3600
  resetpassword:
    sendCaptchaLimit: 60
    captchaExpire: 25

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customer-service
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.98.1:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8
    username: dbuser
    password: 12345678
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

  redis:
    database: 0
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000
    host: localhost

mybatis:
  type-aliases-package: cn.edu.xmu.other.customer.model.po
  mapper-locations: classpath*:cn.edu.xmu.other.customer.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

rocketmq:
  name-server: 119.3.225.71:9876
  producer:
    group: coustomer_group
    max-message-size: 4096
    send-message-timeout: 3000

