package cn.edu.xmu.other.customer.mapper;

import cn.edu.xmu.other.customer.model.po.RegionPo;
import cn.edu.xmu.other.customer.model.po.RegionPoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RegionPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int insert(RegionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int insertSelective(RegionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    List<RegionPo> selectByExample(RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    RegionPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RegionPo record, @Param("example") RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RegionPo record, @Param("example") RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RegionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RegionPo record);
}