package cn.edu.xmu.other.liquidation.mapper;

import cn.edu.xmu.other.liquidation.model.po.ExpenditurePo;
import cn.edu.xmu.other.liquidation.model.po.ExpenditurePoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpenditurePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int insert(ExpenditurePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int insertSelective(ExpenditurePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    List<ExpenditurePo> selectByExample(ExpenditurePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    ExpenditurePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExpenditurePo record, @Param("example") ExpenditurePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExpenditurePo record, @Param("example") ExpenditurePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExpenditurePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oomall_expenditure_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExpenditurePo record);
}